
import { Job, JobCategory, Applicant, SeekerAlert } from './types';

export const TAMILNADU_CENTER = { lat: 11.1271, lng: 78.6569 };
export const CHENNAI_CENTER = { lat: 13.0827, lng: 80.2707 };

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Warehouse Helper',
    company: 'Chennai Logistics Hub',
    category: JobCategory.LOCAL,
    salary: '₹18,000 - ₹22,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 13.1488, lng: 80.2306, address: 'Madhavaram High Rd', area: 'Madhavaram' },
    skills_required: ['Lifting', 'Inventory Management'],
    urgent: true,
    posted_at: '2024-05-10T10:00:00Z',
    description: 'Immediate joining for warehouse operations in Madhavaram hub.',
    status: 'OPEN'
  },
  {
    id: '2',
    title: 'Fullstack Developer',
    company: 'Global Tech OMR',
    category: JobCategory.IT,
    salary: '₹12L - ₹18L PA',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experience: 'SENIOR',
    location: { lat: 12.9010, lng: 80.2279, address: 'Sholinganallur IT Park', area: 'Sholinganallur' },
    skills_required: ['React.js', 'Node.js', 'PostgreSQL', 'TypeScript'],
    urgent: false,
    posted_at: '2024-05-09T08:30:00Z',
    description: 'Looking for a senior developer with experience in modern web stacks.',
    status: 'OPEN'
  },
  {
    id: '3',
    title: 'Store Sales Executive',
    company: 'Sree Krishna Sweets',
    category: JobCategory.LOCAL,
    salary: '₹15,000 - ₹18,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 13.0405, lng: 80.2337, address: 'Pondy Bazaar', area: 'T. Nagar' },
    skills_required: ['Customer Service', 'Tamil Fluency'],
    urgent: true,
    posted_at: '2024-05-11T14:15:00Z',
    description: 'Sales assistant for our flagship T. Nagar store.',
    status: 'OPEN'
  },
  {
    id: '4',
    title: 'React Native Engineer',
    company: 'ZOHO Corp',
    category: JobCategory.IT,
    salary: '₹10L - ₹15L PA',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experience: 'MID',
    location: { lat: 12.8230, lng: 80.0441, address: 'Estancia IT Park', area: 'Guduvanchery' },
    skills_required: ['React Native', 'Mobile UI', 'JavaScript'],
    urgent: false,
    posted_at: '2024-05-11T09:00:00Z',
    description: 'Build mobile applications for our global ecosystem.',
    status: 'PENDING'
  },
  {
    id: '5',
    title: 'Python Data Engineer',
    company: 'Ind Estate Solutions',
    category: JobCategory.IT,
    salary: '₹8L - ₹12L PA',
    type: 'CONTRACT',
    workMode: 'ON_SITE',
    experience: 'MID',
    location: { lat: 13.0116, lng: 80.2207, address: 'Guindy Industrial Estate', area: 'Guindy' },
    skills_required: ['Python', 'Pandas', 'SQL'],
    urgent: false,
    posted_at: '2024-05-08T11:45:00Z',
    description: 'Data processing in the heart of Guindy.',
    status: 'OPEN'
  },
  {
    id: '6',
    title: 'Textile Machine Operator',
    company: 'Coimbatore Fabrics Ltd',
    category: JobCategory.LOCAL,
    salary: '₹16,000 - ₹20,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 11.0168, lng: 76.9558, address: 'Avinashi Road', area: 'Coimbatore' },
    skills_required: ['Machine Operation', 'Quality Check'],
    urgent: true,
    posted_at: '2024-05-12T10:00:00Z',
    description: 'Skilled operators needed for textile manufacturing unit in Coimbatore.',
    status: 'OPEN'
  },
  {
    id: '7',
    title: 'Java Backend Developer',
    company: 'Madurai Software Park',
    category: JobCategory.IT,
    salary: '₹6L - ₹10L PA',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experience: 'MID',
    location: { lat: 9.9252, lng: 78.1198, address: 'IT Park, Madurai', area: 'Madurai' },
    skills_required: ['Java', 'Spring Boot', 'MySQL'],
    urgent: false,
    posted_at: '2024-05-11T11:00:00Z',
    description: 'Join our growing backend team in the temple city.',
    status: 'OPEN'
  },
  {
    id: '8',
    title: 'Logistics Coordinator',
    company: 'Trichy Transports',
    category: JobCategory.LOCAL,
    salary: '₹20,000 - ₹25,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 10.7905, lng: 78.7047, address: 'Central Bus Stand Area', area: 'Trichy' },
    skills_required: ['Coordination', 'Communication'],
    urgent: false,
    posted_at: '2024-05-10T09:00:00Z',
    description: 'Managing logistics and fleet operations in Trichy.',
    status: 'OPEN'
  },
  {
    id: '9',
    title: 'Frontend Architect',
    company: 'Salem Tech Solutions',
    category: JobCategory.IT,
    salary: '₹15L - ₹22L PA',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experience: 'LEAD',
    location: { lat: 11.6643, lng: 78.1460, address: 'Steel Plant Road', area: 'Salem' },
    skills_required: ['React', 'Architecture', 'Performance Tuning'],
    urgent: true,
    posted_at: '2024-05-12T15:30:00Z',
    description: 'Senior role for Salem-based product company.',
    status: 'OPEN'
  },
  {
    id: '10',
    title: 'Quality Control Inspector',
    company: 'Hosur Auto Parts',
    category: JobCategory.LOCAL,
    salary: '₹22,000 - ₹28,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'MID',
    location: { lat: 12.7409, lng: 77.8253, address: 'SIPCOT Phase II', area: 'Hosur' },
    skills_required: ['QC', 'Mechanical Knowledge'],
    urgent: false,
    posted_at: '2024-05-09T14:00:00Z',
    description: 'Ensuring quality in automotive component manufacturing.',
    status: 'OPEN'
  },
  {
    id: 'local_1',
    title: 'Food Delivery Executive',
    company: 'Zomato Chennai',
    category: JobCategory.LOCAL,
    salary: '₹20,000 - ₹35,000',
    type: 'PART_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 13.0645, lng: 80.2457, address: 'Nungambakkam High Rd', area: 'Nungambakkam' },
    skills_required: ['Driving License', 'Smartphone Usage', 'Punctuality'],
    urgent: true,
    posted_at: '2024-05-13T08:00:00Z',
    description: 'Incentive-based delivery roles in the central hub.',
    status: 'OPEN'
  },
  {
    id: 'local_2',
    title: 'Supermarket Supervisor',
    company: 'Nilgiris Store',
    category: JobCategory.LOCAL,
    salary: '₹25,000 - ₹30,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'MID',
    location: { lat: 12.9850, lng: 80.2435, address: 'LB Road', area: 'Adyar' },
    skills_required: ['Retail Management', 'Inventory', 'Leadership'],
    urgent: false,
    posted_at: '2024-05-12T11:30:00Z',
    description: 'Supervising floor staff and stock management.',
    status: 'OPEN'
  },
  {
    id: 'employer_1',
    title: 'Home Nurse / Caregiver',
    company: 'Private Healthcare Home',
    category: JobCategory.LOCAL,
    salary: '₹28,000 - ₹32,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'MID',
    location: { lat: 13.0475, lng: 80.2410, address: 'Sterling Road', area: 'Chetpet' },
    skills_required: ['Nursing', 'First Aid', 'Patience'],
    urgent: true,
    posted_at: '2024-05-13T10:00:00Z',
    description: 'Looking for a dedicated caregiver for an elderly patient.',
    status: 'OPEN',
    employerId: 'employer_mock_uid_1'
  },
  {
    id: 'employer_2',
    title: 'Junior UI Designer',
    company: 'Pixel Perfect Chennai',
    category: JobCategory.IT,
    salary: '₹5L - ₹8L PA',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experience: 'ENTRY',
    location: { lat: 13.0298, lng: 80.2110, address: 'Ekkatuthangal', area: 'Guindy' },
    skills_required: ['Figma', 'UI Design', 'Web Design'],
    urgent: false,
    posted_at: '2024-05-12T09:00:00Z',
    description: 'Join our creative boutique agency.',
    status: 'OPEN',
    employerId: 'employer_mock_uid_1'
  },
  {
    id: 'local_3',
    title: 'Hardware Store Assistant',
    company: 'Vaanavil Hardware',
    category: JobCategory.LOCAL,
    salary: '₹12,000 - ₹15,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 13.0410, lng: 80.1990, address: 'Arcot Road', area: 'Valasaravakkam' },
    skills_required: ['Inventory', 'Tamil Speaking', 'Customer Support'],
    urgent: false,
    posted_at: '2024-05-14T10:00:00Z',
    description: 'Help with sales and inventory at our general hardware store.',
    status: 'OPEN'
  },
  {
    id: 'local_4',
    title: 'Security Guard',
    company: 'SafeGuard Services',
    category: JobCategory.LOCAL,
    salary: '₹18,000 - ₹20,000',
    type: 'FULL_TIME',
    workMode: 'ON_SITE',
    experience: 'ENTRY',
    location: { lat: 12.9249, lng: 80.1000, address: 'GST Road', area: 'Tambaram' },
    skills_required: ['Vigilance', 'Physical Fitness', 'ID Checking'],
    urgent: true,
    posted_at: '2024-05-14T08:30:00Z',
    description: 'Night shift security for a private commercial complex.',
    status: 'OPEN'
  },
  {
    id: 'employer_3',
    title: 'React Developer',
    company: 'Software Craftsmen',
    category: JobCategory.IT,
    salary: '₹14L - ₹20L PA',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experience: 'SENIOR',
    location: { lat: 13.0675, lng: 80.2376, address: 'Kodambakkam IT Hub', area: 'Kodambakkam' },
    skills_required: ['React', 'Next.js', 'Redux', 'Tailwind'],
    urgent: false,
    posted_at: '2024-05-14T12:00:00Z',
    description: 'Lead our frontend architecture for new e-commerce project.',
    status: 'OPEN',
    employerId: 'employer_mock_uid_1'
  }
];

export const MOCK_APPLICANTS: Applicant[] = [
  { id: 'a1', name: 'Arun Balaji', jobTitle: 'Delivery Executive', distance: '1.8 km', matchScore: 88, status: 'NEW', avatar: 'https://i.pravatar.cc/150?u=a1' },
  { id: 'a2', name: 'Suresh Raina', jobTitle: 'Java Developer', distance: '12 km', matchScore: 92, status: 'SHORTLISTED', avatar: 'https://i.pravatar.cc/150?u=a2' },
  { id: 'a3', name: 'Priya Subramanian', jobTitle: 'Accountant', distance: '0.4 km', matchScore: 75, status: 'INTERVIEWED', avatar: 'https://i.pravatar.cc/150?u=a3' }
];

export const MOCK_ALERTS: SeekerAlert[] = [
  { id: 'al1', title: 'Warehouse Helper', company: 'Chennai Logistics', distance: '0.8km away', type: 'URGENT', salary: '₹18,000 - ₹22,000' },
  { id: 'al2', title: 'Fullstack Developer', company: 'Global Tech OMR', distance: '5km away', type: 'MATCH', salary: '₹12L - ₹18L PA' }
];
